//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haircute
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tBook()
        {
            this.tComment = new HashSet<tComment>();
        }
    
        public int fid { get; set; }
        public Nullable<System.DateTime> fDateTime { get; set; }
        public string fPhone { get; set; }
        public string fAddress { get; set; }
        public string fName { get; set; }
        public string fBookNumber { get; set; }
        public Nullable<int> fk_Service { get; set; }
        public Nullable<int> fk_Member { get; set; }
        public Nullable<int> fk_Designer { get; set; }
    
        public virtual tMember tMember { get; set; }
        public virtual tService tService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tComment> tComment { get; set; }
        public virtual tDesigner tDesigner { get; set; }
    }
}
