//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haircute
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMember
    {
        public int fID { get; set; }
        public string fPwd { get; set; }
        public string fUsername { get; set; }
        public string fEmail { get; set; }
        public string fPhone { get; set; }
        public string fGender { get; set; }
        public Nullable<System.DateTime> fBirth { get; set; }
        public string fArea { get; set; }
        public string fDesign { get; set; }
        public Nullable<int> fk_Designer { get; set; }
        public Nullable<int> fk_Memorder { get; set; }
    }
}
