//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haircute
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMember()
        {
            this.tBook = new HashSet<tBook>();
            this.tLike = new HashSet<tLike>();
            this.tDesigner = new HashSet<tDesigner>();
            this.tComment = new HashSet<tComment>();
        }
    
        public int fID { get; set; }
        public string fPwd { get; set; }
        public string fUsername { get; set; }
        public string fEmail { get; set; }
        public string fPhone { get; set; }
        public string fGender { get; set; }
        public Nullable<System.DateTime> fBirth { get; set; }
        public string fArea { get; set; }
        public string fDesign { get; set; }
        public string fNickname { get; set; }
        public string fCity { get; set; }
        public string fconfirmation { get; set; }
        public string fHeadstack { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBook> tBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLike> tLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDesigner> tDesigner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tComment> tComment { get; set; }
    }
}
